blank_issues_enabled: false
contact_links:
  - name: Chat with the Community on SimpleX / Propose new ideas
    url: 'https://smp14.simplex.im/c#huQ65mF5BdP6HJ7wCfByVkwy6w2zghW3WF-YLK8O5wc'
    about: Do not use for issue reports
